### PR TITLE
Issue #54: resolve CRITICAL: invalid defaults

### LINKED ISSUE #54: CRITICAL: invalid defaults
The following defaults raise exceptions when used in SQ checks. Hence, default SQ configuration does not work.

- HeaderCheck & RegexpHeaderCheck: `illegal value 'null' for property 'headerFile'`
- DescendantTokenCheck: `illegal value 'java.lang.Integer.MAX_VALUE' for property 'maximumDepth'`; `Error converting from 'String' to 'Integer' For input string: "java.lang.Integer.MAX_VALUE"`
- ImportControlCheck: `illegal value 'null' for property 'file'`
- SuppressWarningsHolderCheck: `Unable to instantiate 'SuppressWarningsHolderCheck' class, it is also not possible to instantiate it as .SuppressWarningsHolderCheck, SuppressWarningsHolderCheckCheck, .SuppressWarningsHolderCheckCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.`

### PR DESCRIPTION
**Pull request by gaurabdg**
Fix #54

### CODE REVIEW

**Review by muhlba91 — APPROVED** [review]

File: src/main/java/org/example/JavadocMetadataScraper.java [hunk 1]
```diff
@@ -174,7 +174,11 @@ private static ModulePropertyDetails createProperties(DetailNode nodeLi) {
             modulePropertyDetails.setValidationType(getTagTextFromProperty(nodeLi,
                     validationTypeNode));
         }
-        modulePropertyDetails.setDefaultValue(getPropertyDefaultText(nodeLi));
+        final String defaultValue = getPropertyDefaultText(nodeLi);
+        if (!"null".equals(defaultValue)
+            && !"the charset property of the parent".equals(defaultValue)) {
```
Comment (muhlba91) [inline src/main/java/org/example/JavadocMetadataScraper.java:179]: maybe we can be a bit less specific by doing something like `!default.contains("charset property")`?
think about it if it makes sense in this context but also like this it's good to me. :)

Comment (romani) [reply src/main/java/org/example/JavadocMetadataScraper.java:179]: lets be as is  .... to not match something else by chance ....
we will try to resolve this hack later on.
